-- 자유 게시판 댓글 (spec 2-1 §2-1-8, 3-2 §3-2-6, #347).
CREATE TABLE post_comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 게시글이 지워지면 댓글도 함께 지운다 (3-3 결정 23 D4) — 댓글만 남기면
    -- 존재하지 않는 글을 가리키는 고아 행이 된다.
    post_id    BIGINT       NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    content    TEXT         NOT NULL,
    -- 게시글과 같은 판단이다 (2-2 §2-2-4) — 회원을 지워도 댓글은 남기고, NULL이면
    -- "탈퇴한 회원"으로 표시한다.
    author_id  BIGINT REFERENCES users (id) ON DELETE SET NULL,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    -- 댓글은 게시글보다 가벼운 콘텐츠라 상한을 더 낮게 잡는다 (3-3 결정 23 D1).
    CONSTRAINT post_comments_content_length_check CHECK (LENGTH(content) <= 2000)
);

-- 댓글은 대화 순서로 읽는다 — 게시글 목록과 반대로 오래된 것이 위다.
CREATE INDEX idx_post_comments_post_created_id ON post_comments (post_id, created_at ASC, id ASC);
