-- 인증은 구글이 담당한다. 비밀번호 컬럼이 없다 (spec 3-3 결정 13).
-- 신원 키는 email이 아니라 google_sub다 — 이메일은 학교 정책에 따라 바뀔 수 있다.
CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_sub  VARCHAR(255) NOT NULL UNIQUE,
    email       VARCHAR(255) NOT NULL UNIQUE,
    -- 구글이 학번을 주지 않는다. 계정 생성 시점에는 비어 있고 신청서 제출 시 채운다.
    -- UNIQUE는 유지한다 — PostgreSQL은 NULL을 서로 다른 값으로 보므로
    -- 미신청 계정이 여럿이어도 충돌하지 않는다.
    student_no  VARCHAR(20)  UNIQUE,
    name        VARCHAR(50)  NOT NULL,
    role        VARCHAR(10)  NOT NULL DEFAULT 'USER' CHECK (role IN ('USER', 'ADMIN')),
    status      VARCHAR(10)  NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'ACTIVE', 'SUSPENDED')),
    -- 계정 생성일시(첫 구글 로그인). "가입 신청일"은 applied_at이다.
    created_at  TIMESTAMP    NOT NULL,
    applied_at  TIMESTAMP,
    approved_at TIMESTAMP,
    -- 낙관적 잠금. 신청서 제출과 관리자 승인이 같은 행을 동시에 고치면 한쪽만 성공해야
    -- 한다 (spec 3-1 §3-1-4). 인메모리 status 검사만으로는 두 트랜잭션이 모두 통과한다.
    version     BIGINT       NOT NULL DEFAULT 0
);

CREATE TABLE notices (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(200) NOT NULL,
    content    TEXT         NOT NULL,
    is_pinned  BOOLEAN      NOT NULL DEFAULT FALSE,
    author_id  BIGINT REFERENCES users (id),
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL
);

CREATE INDEX idx_notices_pinned_created ON notices (is_pinned DESC, created_at DESC);
