-- Spring Session JDBC 스키마.
--
-- 세션은 RDS에 둔다 (spec 3-1 §3-1-5 MUST). ECS 태스크가 Fargate Spot이라 메모리에 두면
-- 회수될 때 전원이 로그아웃된다.
--
-- 아래는 spring-session-jdbc 3.5.7의 org/springframework/session/jdbc/schema-postgresql.sql을
-- 그대로 옮긴 것이다. 손으로 고치지 않는다 -- 컬럼 하나만 어긋나도 세션 저장이 런타임에 실패한다.
-- Spring Session 버전을 올릴 때는 그 jar의 스키마와 대조하고, 달라졌으면 V3로 새 마이그레이션을
-- 만든다. `spring.session.jdbc.initialize-schema: never`로 두었으므로 스키마 생성은 Flyway 몫이다.

CREATE TABLE SPRING_SESSION (
	PRIMARY_ID CHAR(36) NOT NULL,
	SESSION_ID CHAR(36) NOT NULL,
	CREATION_TIME BIGINT NOT NULL,
	LAST_ACCESS_TIME BIGINT NOT NULL,
	MAX_INACTIVE_INTERVAL INT NOT NULL,
	EXPIRY_TIME BIGINT NOT NULL,
	PRINCIPAL_NAME VARCHAR(100),
	CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
	SESSION_PRIMARY_ID CHAR(36) NOT NULL,
	ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
	ATTRIBUTE_BYTES BYTEA NOT NULL,
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
	CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);
