-- Post Launch(자료·즐겨찾기·활동사진)가 쓸 스키마. spec/3-2-DESIGN-CONTRACT.md §3-2-2가 원본이다.
--
-- 엔티티는 아직 없다 — 이 마이그레이션은 스키마만 미리 만들어 둔다 (#51). 이후 기능 이슈에서
-- 엔티티가 이 테이블에 매핑되면 ddl-auto=validate가 실제로 이 정의를 검증한다.
CREATE TABLE notes (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category     VARCHAR(10)   NOT NULL CHECK (category IN ('EXAM', 'SUBJECT')),
    title        VARCHAR(200)  NOT NULL,
    subject_name VARCHAR(100)  NOT NULL,
    professor    VARCHAR(50),
    year         INT           NOT NULL,
    semester     VARCHAR(10)   NOT NULL CHECK (semester IN ('SPRING', 'FALL')),
    exam_type    VARCHAR(10)   CHECK (exam_type IN ('MIDTERM', 'FINAL')),
    -- 회원을 지워도 자료는 남긴다 (2-2 §2-2-4 MUST) — NULL이면 "탈퇴한 회원"으로 표시한다.
    -- 기본값(NO ACTION)으로 두면 자료를 한 번이라도 올린 회원은 삭제 자체가 막힌다.
    uploader_id  BIGINT REFERENCES users (id) ON DELETE SET NULL,
    created_at   TIMESTAMP     NOT NULL,
    updated_at   TIMESTAMP     NOT NULL,
    -- category=EXAM이면 exam_type이 있어야 하고, SUBJECT면 없어야 한다. 애플리케이션
    -- 검증에만 맡기지 않는다 (spec 3-2 §3-2-2 MUST).
    CONSTRAINT notes_category_exam_type_check CHECK (
        (category = 'EXAM' AND exam_type IS NOT NULL) OR
        (category = 'SUBJECT' AND exam_type IS NULL)
    )
);

CREATE INDEX idx_notes_category_created ON notes (category, created_at);
CREATE INDEX idx_notes_subject_name ON notes (subject_name);
CREATE INDEX idx_notes_year_semester ON notes (year, semester);

CREATE TABLE note_files (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id       BIGINT        NOT NULL REFERENCES notes (id) ON DELETE CASCADE,
    original_name VARCHAR(255)  NOT NULL,
    stored_path   VARCHAR(500)  NOT NULL,
    size_bytes    BIGINT        NOT NULL
);

CREATE TABLE bookmarks (
    user_id    BIGINT    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    note_id    BIGINT    NOT NULL REFERENCES notes (id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL,
    -- 복합 PK로 (회원, 자료) 중복 등록을 막는다 (spec 3-2 §3-2-2).
    PRIMARY KEY (user_id, note_id)
);

CREATE TABLE photos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caption     VARCHAR(200),
    stored_path VARCHAR(500) NOT NULL,
    -- notes.uploader_id와 같은 이유로 SET NULL이다 — 관리자도 삭제 대상이 될 수 있고
    -- 활동사진은 아카이브라 남아야 한다 (2-2 §2-2-4 MUST).
    uploader_id BIGINT REFERENCES users (id) ON DELETE SET NULL,
    created_at  TIMESTAMP    NOT NULL
);
