-- 관리자 조작 이력 (#143, spec 2-2 §2-2-7).
--
-- "누가 누구를 언제 정지했나"에 답하기 위한 것이다. 그동안은 log.info로만 남았고,
-- 그 로그는 CloudWatch에 있어 보존 기간이 지나면 사라진다. 승인·정지·승격은 되돌릴 수는
-- 있지만 분쟁이 생기는 조작이라 근거가 남아야 한다.
CREATE TABLE admin_actions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 조작한 사람과 대상. 둘 다 users.id지만 FK를 걸지 않는다.
    --
    -- 이 저장소의 다른 테이블은 users를 가리킬 때 ON DELETE SET NULL이다 (2-2 §2-2-4).
    -- 여기에 같은 규칙을 쓰면 회원을 지우는 순간 "누구를 정지했는지"가 사라져 이력의
    -- 존재 이유가 무너진다. 자료·공지와 성격이 다르다 — 그쪽은 보여줄 콘텐츠라 작성자
    -- 표시가 필요하지만, 이력은 일어난 일의 기록이라 현재 상태에 종속되면 안 된다.
    --
    -- 이름·이메일 같은 스냅샷은 두지 않는다. 계정을 지운 뒤에도 개인정보가 남는다.
    -- 남는 것은 숫자 id뿐이다.
    actor_id   BIGINT       NOT NULL,
    target_id  BIGINT       NOT NULL,
    action     VARCHAR(20)  NOT NULL CHECK (
        action IN ('APPROVE', 'SUSPEND', 'ACTIVATE', 'PROMOTE_ADMIN')
    ),
    created_at TIMESTAMP    NOT NULL
);

-- "이 사람에게 무슨 일이 있었나"가 주된 질문이다. 두 번째는 "이 관리자가 무엇을 했나".
CREATE INDEX idx_admin_actions_target ON admin_actions (target_id, created_at DESC);
CREATE INDEX idx_admin_actions_actor ON admin_actions (actor_id, created_at DESC);
