-- 관리자 승격 실패 시도 (#144, spec 3-3 결정 11).
--
-- POST /auth/bootstrap-admin은 로그인만 하면 누구나 부를 수 있고 방어선은 "활성 관리자 0명"
-- 하나다. 그 조건이 성립하는 순간 — 최초 배포 직후, 관리자 사고 복구 중 — 은 정확히
-- 아무도 막을 수 없는 시점인데, 그때 토큰을 무제한으로 추측할 수 있었다.
--
-- 성공한 조작을 남기는 admin_actions와 섞지 않는다 (#143이 "성공한 조작만"으로 경계를
-- 그었다). 목적도 보존 주기도 다르다 — 이력은 영구히 남고, 이 표는 창이 지나면 버린다.
CREATE TABLE admin_bootstrap_attempts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 시도한 계정. admin_actions와 같은 이유로 users FK를 걸지 않는다 — 계정이 사라져도
    -- "그때 몇 번 두드렸나"는 남아야 하고, 잠금 판단이 users의 생명주기에 묶이면 안 된다.
    account_id BIGINT    NOT NULL,
    created_at TIMESTAMP NOT NULL
);

-- 계정별 창 조회와 전역 창 조회 둘 다 시각으로 자른다.
CREATE INDEX idx_bootstrap_attempts_account ON admin_bootstrap_attempts (account_id, created_at);
CREATE INDEX idx_bootstrap_attempts_time ON admin_bootstrap_attempts (created_at);
