-- 자유 게시판 (spec 2-1 §2-1-8, 3-2 §3-2-2, #235·#236).
CREATE TABLE posts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(200) NOT NULL,
    content    TEXT         NOT NULL,
    -- 회원을 지워도 글은 남긴다 (2-2 §2-2-4 MUST) — NULL이면 "탈퇴한 회원"으로 표시한다.
    --
    -- 이 절이 빠지면 기본값(NO ACTION)이 되어 글을 한 번이라도 쓴 회원은 삭제 자체가
    -- FK 위반으로 실패한다. notices.author_id가 정확히 그 상태로 만들어져 V7에서
    -- 뒤늦게 고쳤다 (#58). 같은 실수를 두 번 하지 않는다.
    author_id  BIGINT REFERENCES users (id) ON DELETE SET NULL,
    created_at TIMESTAMP    NOT NULL,
    updated_at TIMESTAMP    NOT NULL,
    -- 본문 상한을 DB에서도 막는다 (3-2 §3-2-2 MUST). 요청 검증만 두면 다른 경로로
    -- 들어온 값이 그대로 저장되고, 글 하나로 목록 응답이 망가진다. TEXT는 무제한이다.
    CONSTRAINT posts_content_length_check CHECK (LENGTH(content) <= 10000)
);

-- 목록의 고정 정렬과 같다 (created_at DESC, id DESC).
CREATE INDEX idx_posts_created_id ON posts (created_at DESC, id DESC);
